# Generated by Django 4.2.6 on 2023-10-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_buildingconsumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingconsumption',
            name='attic_consumption',
        ),
        migrations.RemoveField(
            model_name='buildingconsumption',
            name='basement_consumption',
        ),
        migrations.RemoveField(
            model_name='buildingconsumption',
            name='ground_floor_consumption',
        ),
        migrations.RemoveField(
            model_name='buildingconsumption',
            name='heating_consumption',
        ),
        migrations.RemoveField(
            model_name='buildingconsumption',
            name='house_consumption',
        ),
        migrations.RemoveField(
            model_name='buildingconsumption',
            name='water_consumption',
        ),
        migrations.AddField(
            model_name='buildingconsumption',
            name='month',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildingconsumption',
            name='year',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
