# Generated by Django 4.2.6 on 2023-10-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_buildingconsumption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuildingConsumption',
        ),
    ]
