# Generated by Django 4.2.6 on 2023-10-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_buildingconsumption'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('house_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ground_floor_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attic_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('basement_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('heating_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
