# Generated by Django 4.2.6 on 2023-10-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_energyconsumption_total_kwh'),
        ('app', '0004_buildingconsumption'),
    ]

    operations = [
    ]
