# Generated by Django 4.2.6 on 2023-10-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20231026_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingconsumption',
            name='attic_consumption',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='buildingconsumption',
            name='basement_consumption',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='buildingconsumption',
            name='ground_floor_consumption',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='buildingconsumption',
            name='heating_consumption',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='buildingconsumption',
            name='house_consumption',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='buildingconsumption',
            name='water_consumption',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='buildingconsumption',
            name='total_consumption',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
