# Generated by Django 4.2.6 on 2023-11-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_buildingconsumption_attic_consumption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingConsumptionEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
            ],
        ),
    ]
