# Generated by Django 4.2.6 on 2023-11-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_buildingconsumptionenergy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuildingConsumptionEnergy',
        ),
    ]
