# Generated by Django 4.2.6 on 2023-11-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_buildingconsumption_house_consumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingconsumption',
            name='house_consumption',
        ),
    ]
